### ISSUE TITLE
Vision's Passive image is incorrect

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#16]
![image](https://user-images.githubusercontent.com/11431194/44367841-c525e200-a485-11e8-8436-6c85d387381b.png)

It's AIM Infector's basic right now :(

**Comment by tyejae** [comment]
Doh, thanks for the heads up. I'll fix this.

**Comment by chronolinq** [comment]
Some more data points:

![image](https://user-images.githubusercontent.com/11431194/44607658-14318700-a7a6-11e8-8077-8f43e4a7186a.png)
![image](https://user-images.githubusercontent.com/11431194/44607668-1f84b280-a7a6-11e8-904a-7745d51c7094.png)
![image](https://user-images.githubusercontent.com/11431194/44607710-3d521780-a7a6-11e8-8f99-e95fe42d7f38.png)

**Comment by tyejae** [comment]
Fixed them all with the new update

**Comment by chronolinq** [comment]
Looks like Iron Man's Stark Upgrades image is still incorrect :(

Others look good though!
